# https://hub.docker.com/_/ubuntu
FROM ubuntu:20.04 


RUN set -xe && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && apt-get -qqy upgrade

RUN set -xe && \
    apt-get install libpcap-dev masscan -y

ENTRYPOINT ["masscan"]
CMD ["-h"]
